# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20180108_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wish_list',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
