# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20180108_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_store', models.BooleanField()),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shopping.Cart')),
                ('wish_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='shopping.WishList')),
            ],
        ),
    ]
