# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_auto_20180108_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='shopping.Cart'),
        ),
        migrations.AddField(
            model_name='user',
            name='wish_list',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to='shopping.WishList'),
        ),
    ]
