# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20180110_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('products', models.ManyToManyField(related_name='sell', to='shopping.Product')),
            ],
        ),
    ]
