# Generated by Django 2.0.1 on 2018-01-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_cart_buyer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='user_id',
        ),
    ]
