# Generated by Django 2.0.1 on 2018-01-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20180110_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
